name: Cron Jobs

on:
  schedule:
    - cron: "45 13 * * *"
    - cron: "0 0 * * *"

jobs:
  call-vercel-api-1:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cron Job 1
        run: |
          curl -X GET https://night-owl-seven.vercel.app/api/run-cron-remaining-days

  call-vercel-api-2:
    runs-on: ubuntu-latest
    steps:
      - name: Call Cron Job 2
        run: |
          curl -X GET https://night-owl-seven.vercel.app/api/checkAndUpdateDayOffs
